# Automatically generated by configure - do not modify
targets=beautify
prefix=/home/cs-students/04thw/usr
MAKE=make
CC=mpiCC
beautify_config_args=--enable-mpi
CCFLAGS=-I/home/cs-students/04thw/usr/include -I /include -fomit-frame-pointer -finline-functions -I/home/scratch/04thw/graphics/beautify -I/home/scratch/04thw/graphics/beautify/src -I/home/scratch/04thw/graphics/beautify/src/Functions
LDFLAGS=-L/home/cs-students/04thw/usr/lib
MPI=yes
