# Automatically generated by configure - do not modify
targets=beautify
prefix=/usr/local
MAKE=make
CC=g++
beautify_config_args=
CCFLAGS=-O3 -I/home/tom/code/owns/beautify/include/Functions -I/home/tom/code/owns/beautify/include/linAlgLib -Wno-endif-labels -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -fopenmp -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -I/usr/include/x86_64-linux-gnu//ImageMagick-6 -I/usr/include/ImageMagick-6 -fomit-frame-pointer -finline-functions -I/home/tom/code/owns/beautify -I/home/tom/code/owns/beautify/src -I/home/tom/code/owns/beautify/src/Functions
LDFLAGS= -lMagick++-6.Q16 -lMagickWand-6.Q16 -lMagickCore-6.Q16
