# Automatically generated by configure - do not modify
targets=bill tom beautify
prefix=/usr/local
MAKE=make
CC=g++
beautify_config_args=
CCFLAGS=-O3 -I/home/tom/code/beautify/include/Functions -I/home/tom/code/beautify/include/linAlgLib -fomit-frame-pointer -finline-functions -I/home/tom/code/beautify -I/home/tom/code/beautify/src -I/home/tom/code/beautify/src/Functions
LDFLAGS=
