# makefile for Transform4Df

# (C) Bill Lenhart 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = Transform4Df
USESCLASSES = ../Point4Df/Point4Df.o ../Point3Df/Point3Df.o ../Transform3Df/Transform3Df.o

include ../include.mak














