# makefile for Shape

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = Sphere
USESCLASSES =  ../Shape/Shape.o ../Ray/Ray.o
IFILE = includeFinal.mak

include ../include.mak














