# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=gmake
CC=g++
OPTFLAGS=-O3 -fomit-frame-pointer -finline-functions
LDFLAGS=
CCFLAGS=-O3 -fomit-frame-pointer -finline-functions -std=c++03 -Wendif-labels 
