# Automatically generated by configure - do not modify
prefix=/home/cs-students/04thw/usr
MAKE=gmake
CC=g++
OPTFLAGS=-O3 -fomit-frame-pointer -finline-functions
LDFLAGS=
CCFLAGS=-O3 -fomit-frame-pointer -finline-functions 
