# makefile for Light

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = Shader
USESCLASSES =

SUBDIRS = LambertShader/LambertShader.o

include ../include.mak