# makefile for Light

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = PointLight
USESCLASSES = ../Light.o
IFILE=includeFinal.mak

include ../include.mak
