# makefile for Shaders

# (C) Anonymous1 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = LambertShader
USESCLASSES =
IFILE = include.mak
SUBDIRS = PhongShader/PhongShader.o PhongSShader/PhongSShader.o \
PhongSTShader/PhongSTShader.o PhongSRShader/PhongSRShader.o \
PhongSRTShader/PhongSRTShader.o
LOCALCLASSESDIR = ../..

include ../include.mak