# makefile for Shader

# (C) Tom White 

# local variables override values from ../Makefile
# Name of this class
CLASS = PhongSRShader
USESCLASSES =  ../Shape/Shape.o ../Ray/Ray.o ../Shader/Shader.o
IFILE = includeFinal.mak

include ../include.mak














