# makefile for Point4Dd

# (C) Bill Lenhart 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = Point4Dd
USESCLASSES = ../Transform4Dd/Transform4Dd.o ../Point3Dd/Point3Dd.o ../Transform3Dd/Transform3Dd.o

include ../include.mak














