# makefile for Light

# (C) Anonymous1 

# local variables override values from ../Makefile
# Name of this class
CLASS = Light
USESCLASSES =
LOCALCLASSESDIR = ../.. -I..

SUBDIRS = DirLight/DirLight.o PointLight/PointLight.o

include ../include.mak