# makefile for Point4Df

# (C) Bill Lenhart 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = Point4Df
USESCLASSES = ../Transform4Df/Transform4Df.o ../Point3Df/Point3Df.o ../Transform3Df/Transform3Df.o

include ../include.mak














