# makefile for Scene

# (C) Anonymous1 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = Scene
USESCLASSES = ../Surface/Surface.o ../Light/Light.o \
../Light/DirLight/DirLight.o ../Light/PointLight/PointLight.o \
../TransformMaker/TransformMaker.o \
../Shape/Shape.o ../Shape/Sphere/Sphere.o ../Shape/Plane/Plane.o \
../Camera/Camera.o ../Ray/Ray.o ../Renderer/Renderer.o ../Hit/Hit.o \
../Shader/Shader.o ../Shader/LambertShader/LambertShader.o \
../Shader/LambertShader/PhongShader/PhongShader.o \
../Shader/LambertShader/PhongSShader/PhongSShader.o \
../Shader/LambertShader/PhongSTShader/PhongSTShader.o \
../Shader/LambertShader/PhongSRShader/PhongSRShader.o \
../Shader/LambertShader/PhongSRTShader/PhongSRTShader.o \
../Shape/TaperedCyl/TaperedCyl.o

#no derived classes
include ../includeFinal.mak












