# makefile for Shape

# (C) Anonymous1 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = Shape
USESCLASSES = ../Ray/Ray.o ../Sphere/Sphere.o ../Plane/Plane.o
SUBDIRS = Plane/Plane.o Sphere/Sphere.o

include ../include.mak














