# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=gmake
CC=g++
OPTFLAGS=-O3 -std=c++03 -fomit-frame-pointer -finline-functions
LDFLAGS=
CCFLAGS=-O3 -std=c++03 -fomit-frame-pointer -finline-functions  -Wno-endif-labels
