# Automatically generated by configure - do not modify
prefix=/home/cs-students/04thw/usr
MAKE=gmake
CC=g++
OPTFLAGS=-I/home/cs-students/04thw/usr/include -fomit-frame-pointer -finline-functions
LDFLAGS=-L/home/cs-students/04thw/usr/lib
CCFLAGS=-I/home/cs-students/04thw/usr/include -fomit-frame-pointer -finline-functions 
