# Automatically generated by configure - do not modify
prefix=/home/cs-students/04thw/usr
MAKE=make
CC=mpiCC
CCFLAGS= -I/usr/X11R6/include -I/usr/local/include -I/home/cs-students/04thw/usr/include -I /include -fomit-frame-pointer -finline-functions -I/home/scratch/04thw/graphics/beautify/src -I/home/scratch/04thw/graphics/beautify/src/src -I/home/scratch/04thw/graphics/beautify/src/src/Functions -g
LDFLAGS=-llinAlg -lTomFun -lglut -lGLU -lGL -lMagick++ -lMagick  -L/usr/X11R6/lib -L/usr/local/lib -L/home/cs-students/04thw/usr/lib
glut=yes
glutlibs=-lglut -lGL -lGLU
magick=yes
magicklibs=-lMagick++ -lMagick
MPI=yes
