# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
CC=g++
CCFLAGS= -g -I/home/tom/code/beautify/src/include/Functions -I/home/tom/code/beautify/src/include/linAlgLib -I/home/tom/code/beautify/src/../include/Functions -I/home/tom/code/beautify/src/include/linAlgLib -Wno-endif-labels -I/home/tom/code/beautify/src -I/home/tom/code/beautify/src/src -I/home/tom/code/beautify/src/src/Functions
LDFLAGS=-llinAlg -lTomFun -lglut -lGLU -lGL -lMagick++ -lMagick 
glut=yes
glutlibs=-lglut -lGL -lGLU
magick=yes
magicklibs=-lMagick++ -lMagick
