# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
CC=g++
#-03
CCFLAGS= -g -I/disk2/working/graphics/beautify/src/include/Functions -I/disk2/working/graphics/beautify/src/include/linAlgLib -I/disk2/working/graphics/beautify/src -I/disk2/working/graphics/beautify/src/src -I/disk2/working/graphics/beautify/src/src/Functions
LDFLAGS=-llinAlg -lTomFun -lglut -lGLU -lGL -lMagick++ -lMagick 
glut=yes
glutlibs=-lglut -lGL -lGLU
