# makefile for Light

# (C) Anonymous1 2002

# local variables override values from ../Makefile
# Name of this class
CLASS = Renderer
USESCLASSES = ../Scene/Scene.o 

SUBDIRS = 

include ../includeFinal.mak